"""fix tasks updated_at default

Revision ID: 224e6f6c1765
Revises: a8ba0967ceaf
Create Date: 2026-02-01 15:16:01.640259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '224e6f6c1765'
down_revision: Union[str, None] = 'a8ba0967ceaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
